### ISSUE TITLE
Missing AssignmentArithmeticAndComparisonSpaceSniff and AsteriksWhitespacesSniff

### ISSUE THREAD

**Issue by etobi** [typo3-ci/TYPO3Flow#15]
I installed the codesniffer using `composer global require "typo3-ci/typo3flow=dev-master"`
When running phpcs like `~/.composer/vendor/bin/phpcs --standard=~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/TYPO3Flow/ruleset.xml  Packages/Application/Foo.Bar` all i got is an exception:

```
Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "../TYPO3SniffPool/Sniffs/WhiteSpace/AssignmentArithmeticAndComparisonSpaceSniff.php" does not exist' in /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1092
Stack trace:
#0 /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php(733): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/tobias/....', 0)
#1 /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php(551): PHP_CodeSniffer->processRuleset('/Users/tobias/....')
#2 /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(830): PHP_CodeSniffer->initStandard(Array, Array)
#3 /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(95): PHP_CodeSniffer_CLI->process()
#4 /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /Users/tobias/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1092
```

The ruleset.xml in ` ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/TYPO3Flow/ruleset.xml` is referencing two Sniff files, which don't exists.

```
        <rule ref="../TYPO3SniffPool/Sniffs/WhiteSpace/AssignmentArithmeticAndComparisonSpaceSniff.php" />
        <rule ref="../TYPO3SniffPool/Sniffs/WhiteSpace/AsteriksWhitespacesSniff.php" />
```

When removing these two lines from ```ruleset.xml``` the phpcs is running fine. However these checks are missing.

**Comment by kaystrobach** [comment]
i do have the same problem in OSX 10.10:

![2015-05-06_08-54-46](https://cloud.githubusercontent.com/assets/1185776/7488677/d0416018-f3cd-11e4-9479-716db0107f6a.png)
![2015-05-06_08-55-03](https://cloud.githubusercontent.com/assets/1185776/7488679/d48ac0ec-f3cd-11e4-917e-5f52a6ca1737.png)
![2015-05-06_08-55-29](https://cloud.githubusercontent.com/assets/1185776/7488680/d7231692-f3cd-11e4-9010-4966ae5a83ce.png)

**Comment by Konafets** [comment]
I just released version 2.3.0 of this standard. A ```dev-master``` is not necessary at the moment. Here is how my composer.json looks like:

```
$ cat ~/.composer/composer.json
{
    "require": {
        "typo3-ci/TYPO3CMS": "~6.2",
        "typo3-ci/TYPO3Flow": "~2.3"
    }
}
```

@etobi Can you try run PHPCS like this: ```~/.composer/vendor/bin/phpcs --standard=TYPO3Flow Packages/Application/Foo.Bar``` and if this is not working ```~/.composer/vendor/bin/phpcs -i```? 
The latter command should give an output like 

```
$ ~/.composer/vendor/bin/phpcs -i
The installed coding standards are MySource, TYPO3CMS, PEAR, Zend, PSR1, Squiz, TYPO3Flow, PHPCS, PSR2 and TYPO3SniffPool
```

**Comment by kaystrobach** [comment]
@Konafets the problem is the same.

```
bin/phpcs -i
```

gives me:

```
The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz, TYPO3CMS, TYPO3Flow, TYPO3SniffPool and Zend
```

The error is still the same:

```
HP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "../TYPO3SniffPool/Sniffs/WhiteSpace/AssignmentArithmeticAndComparisonSpaceSniff.php" does not exist' in /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer.php:1092
Stack trace:
#0 /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer.php(733): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/kay/Deve...', 0)
#1 /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer.php(551): PHP_CodeSniffer->processRuleset('/Users/kay/Deve...')
#2 /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer/CLI.php(830): PHP_CodeSniffer->initStandard(Array, Array)
#3 /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer/CLI.php(95): PHP_CodeSniffer_CLI->process()
#4 /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_co in /Users/kay/Development/Lapo/project/Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer.php on line 1092
```

**Comment by Konafets** [comment]
@kaystrobach Did you make a ```$ composer update```

**Comment by kaystrobach** [comment]
sure i did:

![2015-05-06_20-41-15](https://cloud.githubusercontent.com/assets/1185776/7500789/442c9b5c-f430-11e4-99c8-8bb6fb3c92d5.png)

I have both standards included in my composer.jsons require-dev part (because no one needs phpcs on a production system) ...

**Comment by kaystrobach** [comment]
I still do not understand, why i should install both standards, if I just need the FLOW standard for testing ...

**Comment by Konafets** [comment]
Please try again. Maybe a ```$ composer cleancache``` helps in case the new version of the standard is not fetched from Packagist.

P.S.: You don't need TYPO3CMS standard for checking only FLOW code. Can you tell me how you get to that conclusion?
P.P.S: Why do you use ```--prefer-source```?

**Comment by kaystrobach** [comment]
works now.

Regarding PS1: just taken from your example, works fine without as well ...

Regarding PS2: I have a multipackage project, where i use a lot of dependencies, which are changed during the development, with ```--prefer-source``` i have git repos for all of them and can directly commit and push, doing a composer update after a push (waiting some seconds) gives me the chance to update the composer.json as well and just do a composer install during deployment ...
